export * from './auth.routes'
export * from './cinemaShow.routes'
export * from './image.routes'
export * from './main.routes'
export * from './movie.routes'
export * from './payment.routes'
export * from './room.routes'
