export * from './auth.controller'
export * from './cinemaShow.controller'
export * from './image.controller'
export * from './movie.controller'
export * from './payment.controller'
export * from './room.controller'
export * from './ticket.controller'
